language: perl
script: prove -lr t xt
install:
- cpanm -n -q
  Test::More
  JSON::PP
perl:
- '5.20'
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
- '5.8'
notifications:
  irc:
    channels:
    - irc.perl.org#yaml
    on_success: change
    on_failure: always
branches:
  except:
  - /^PR/
