#!/usr/bin/env perl

use strict;
use warnings;
use lib 'lib', 't/lib/';
use TestBridge;
use TestMLTiny;
use Test::More 0.99;
use TestUtils;

sub main {
    for my $file (@_) {
        (my $name = $file) =~ s/[\/\.\-]/_/g;
        my $runner = $ENV{"testml_bridge_$name"} ||
            'test_local';
        my $bridge = eval "\\&$runner"; die $@ if $@;
        testml_run_file(
            $file,
            sub {
                my ($file, $blocks) = @_;
                subtest "TestML dev runner: $file" => sub {
                    plan tests => scalar @$blocks;
                    $bridge->($_) for @$blocks;
                };
                done_testing;
            },
        );
    }
}

main @ARGV;
